[package]
name = "agrame"
version = "0.1.0"
edition = "2021"

[dependencies]
yew = { git = "https://github.com/yewstack/yew/", features = ["csr"] }
gloo-console = "0.3.0"
nom = "7.1.3"
web-sys = "0.3.66"

[lib]
name = "agrame"
path = "src/agrame/lib.rs"

[[bin]]
name = "agramex"

